In [1]:
from matplotlib import rcParams
import plotly.tools as tls
import plotly.offline as py
from plotly.offline import init_notebook_mode,iplot,plot
from plotly.graph_objs import *
init_notebook_mode(connected=True)
import warnings

In [2]:
import numpy as np
import pandas as pd

In [3]:
emissions=pd.read_csv('Co2EmissionsPerCapitaByCountry.csv',index_col=0)

In [4]:
emissions.head()

,Year,Afghanistan | AFG,Albania | ALB,Algeria | DZA,American Samoa | ASM,Andorra | AND,Angola | AGO,Antigua and Barbuda | ATG,Arab World | ARB,Argentina | ARG,...,Uzbekistan | UZB,Vanuatu | VUT,"Venezuela, RB | VEN",Vietnam | VNM,Virgin Islands (U.S.) | VIR,West Bank and Gaza | PSE,World | WLD,"Yemen, Rep. | YEM",Zambia | ZMB,Zimbabwe | ZWE
0,1960,0.046068,1.258195,0.553764,NaN,NaN,0.104357,0.670617,0.643964,2.367473,...,NaN,NaN,7.005107,0.215631,NaN,NaN,3.096137,0.703403,NaN,NaN
1,1961,0.053615,1.374186,0.531810,NaN,NaN,0.084718,0.860441,0.685501,2.442616,...,NaN,NaN,6.136886,0.225435,NaN,NaN,3.067052,0.507631,NaN,NaN
2,1962,0.073781,1.439956,0.484954,NaN,NaN,0.216025,1.823374,0.761148,2.522392,...,NaN,0.594888,6.155057,0.258760,NaN,NaN,3.138003,0.728004,NaN,NaN
3,1963,0.074251,1.181681,0.452824,NaN,NaN,0.206877,1.470175,0.875124,2.316356,...,NaN,0.471728,6.155748,0.247579,NaN,NaN,3.242342,0.537606,NaN,NaN
4,1964,0.086317,1.111742,0.459569,NaN,NaN,0.216174,1.567094,0.999248,2.538380,...,NaN,0.864247,5.973226,0.314058,NaN,NaN,3.358670,0.658012,0.950434,1.045374

In [10]:
sumcolumnSelection=['United Arab Emirates | ARE','United Kingdom | GBR','United States | USA',
                  'China | CHN','India | IND','Year']
stackedAreaData=emissions.loc[:,(sumcolumnSelection)]

In [11]:
stackedAreaData.head()

,United Arab Emirates | ARE,United Kingdom | GBR,United States | USA,China | CHN,India | IND,Year
0,0.118786,11.150759,15.999779,1.170381,0.268161,1960
1,0.108937,11.154139,15.681256,0.836047,0.284292,1961
2,0.163355,11.142928,16.013938,0.661428,0.306519,1962
3,0.175712,11.254853,16.482762,0.640002,0.322533,1963
4,0.132651,11.265839,16.968119,0.625646,0.308900,1964

In [14]:
stackedAreaData['Total']=stackedAreaData[sumcolumnSelection].sum(axis=1)

In [15]:
stackedAreaData.head()

,United Arab Emirates | ARE,United Kingdom | GBR,United States | USA,China | CHN,India | IND,Year,Total
0,0.118786,11.150759,15.999779,1.170381,0.268161,1960,1988.707867
1,0.108937,11.154139,15.681256,0.836047,0.284292,1961,1989.064670
2,0.163355,11.142928,16.013938,0.661428,0.306519,1962,1990.288169
3,0.175712,11.254853,16.482762,0.640002,0.322533,1963,1991.875863
4,0.132651,11.265839,16.968119,0.625646,0.308900,1964,1993.301155

In [16]:
for country in sumcolumnSelection:
    stackedAreaData['pc_' + str(country)]=stackedAreaData[country]/stackedAreaData['Total']

In [17]:
stackedAreaData.head()

,United Arab Emirates | ARE,United Kingdom | GBR,United States | USA,China | CHN,India | IND,Year,Total,pc_United Arab Emirates | ARE,pc_United Kingdom | GBR,pc_United States | USA,pc_China | CHN,pc_India | IND,pc_Year
0,0.118786,11.150759,15.999779,1.170381,0.268161,1960,1988.707867,0.000060,0.005607,0.008045,0.000589,0.000135,0.985565
1,0.108937,11.154139,15.681256,0.836047,0.284292,1961,1989.064670,0.000055,0.005608,0.007884,0.000420,0.000143,0.985891
2,0.163355,11.142928,16.013938,0.661428,0.306519,1962,1990.288169,0.000082,0.005599,0.008046,0.000332,0.000154,0.985787
3,0.175712,11.254853,16.482762,0.640002,0.322533,1963,1991.875863,0.000088,0.005650,0.008275,0.000321,0.000162,0.985503
4,0.132651,11.265839,16.968119,0.625646,0.308900,1964,1993.301155,0.000067,0.005652,0.008513,0.000314,0.000155,0.985300

In [20]:
sumcolumnSelectionPC=['pc_United Arab Emirates | ARE','pc_United Kingdom | GBR','pc_United States | USA',
                  'pc_China | CHN','pc_India | IND']

In [21]:
PCAreaData=stackedAreaData[sumcolumnSelectionPC].cumsum(axis=1)

PCAreaData.head()

,pc_United Arab Emirates | ARE,pc_United Kingdom | GBR,pc_United States | USA,pc_China | CHN,pc_India | IND
0,0.000060,0.005667,0.013712,0.014301,0.014435
1,0.000055,0.005662,0.013546,0.013967,0.014109
2,0.000082,0.005681,0.013727,0.014059,0.014213
3,0.000088,0.005739,0.014014,0.014335,0.014497
4,0.000067,0.005718,0.014231,0.014545,0.014700

In [22]:
PCAreaData['Year']=stackedAreaData['Year']

In [23]:
PCAreaData.head()

,pc_United Arab Emirates | ARE,pc_United Kingdom | GBR,pc_United States | USA,pc_China | CHN,pc_India | IND,Year
0,0.000060,0.005667,0.013712,0.014301,0.014435,1960
1,0.000055,0.005662,0.013546,0.013967,0.014109,1961
2,0.000082,0.005681,0.013727,0.014059,0.014213,1962
3,0.000088,0.005739,0.014014,0.014335,0.014497,1963
4,0.000067,0.005718,0.014231,0.014545,0.014700,1964

In [24]:
traces=[]

for col in PCAreaData.columns.tolist():
    if col!='Year':
        traces.append({'type':'scatter',
                       'x':PCAreaData['Year'],
                       'y':PCAreaData[col],
                       'name': col[3:-6],
                       'mode': 'lines',
                       'fill':'tonexty'
                      })

data=Data(traces)
layout={'title':'Proportion of CO2 Emission , 1960-2011',
        'xaxis':{'title':'Year'},
        'yaxis':{'title':'Proportion of co2 Emissions'}}

fig=Figure(data=data,layout=layout)
iplot(fig)

C:\Users\Satish\Anaconda3\lib\site-packages\plotly\graph_objs\_deprecations.py:39: DeprecationWarning:

plotly.graph_objs.Data is deprecated.
Please replace it with a list or tuple of instances of the following types
  - plotly.graph_objs.Scatter
  - plotly.graph_objs.Bar
  - plotly.graph_objs.Area
  - plotly.graph_objs.Histogram
  - etc.